/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables;


import com.example.dao.entity.Keys;
import com.example.dao.entity.Public;
import com.example.dao.entity.tables.records.CustomerInfoTblRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerInfoTbl extends TableImpl<CustomerInfoTblRecord> {

	private static final long serialVersionUID = 910229308;

	/**
	 * The reference instance of <code>PUBLIC.CUSTOMER_INFO_TBL</code>
	 */
	public static final CustomerInfoTbl CUSTOMER_INFO_TBL = new CustomerInfoTbl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CustomerInfoTblRecord> getRecordType() {
		return CustomerInfoTblRecord.class;
	}

	/**
	 * The column <code>PUBLIC.CUSTOMER_INFO_TBL.CUSTOMER_ID</code>.
	 */
	public final TableField<CustomerInfoTblRecord, String> CUSTOMER_ID = createField("CUSTOMER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CUSTOMER_INFO_TBL.KEY</code>.
	 */
	public final TableField<CustomerInfoTblRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.CUSTOMER_INFO_TBL.VAL</code>.
	 */
	public final TableField<CustomerInfoTblRecord, String> VAL = createField("VAL", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.CUSTOMER_INFO_TBL</code> table reference
	 */
	public CustomerInfoTbl() {
		this("CUSTOMER_INFO_TBL", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.CUSTOMER_INFO_TBL</code> table reference
	 */
	public CustomerInfoTbl(String alias) {
		this(alias, CUSTOMER_INFO_TBL);
	}

	private CustomerInfoTbl(String alias, Table<CustomerInfoTblRecord> aliased) {
		this(alias, aliased, null);
	}

	private CustomerInfoTbl(String alias, Table<CustomerInfoTblRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CustomerInfoTblRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CustomerInfoTblRecord>> getKeys() {
		return Arrays.<UniqueKey<CustomerInfoTblRecord>>asList(Keys.CONSTRAINT_C);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerInfoTbl as(String alias) {
		return new CustomerInfoTbl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CustomerInfoTbl rename(String name) {
		return new CustomerInfoTbl(name, null);
	}
}
