/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables.records;


import com.example.dao.entity.tables.CustomerTbl;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CUSTOMER_TBL", schema = "PUBLIC")
public class CustomerTblRecord extends UpdatableRecordImpl<CustomerTblRecord> implements Record3<String, String, Integer> {

	private static final long serialVersionUID = 45002454;

	/**
	 * Setter for <code>PUBLIC.CUSTOMER_TBL.GUID</code>.
	 */
	public void setGuid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUSTOMER_TBL.GUID</code>.
	 */
	@Id
	@Column(name = "GUID", unique = true, nullable = false, length = 100)
	public String getGuid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CUSTOMER_TBL.NAME</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUSTOMER_TBL.NAME</code>.
	 */
	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.CUSTOMER_TBL.AGE</code>.
	 */
	public void setAge(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.CUSTOMER_TBL.AGE</code>.
	 */
	@Column(name = "AGE", nullable = false, precision = 10)
	public Integer getAge() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CustomerTbl.CUSTOMER_TBL.GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CustomerTbl.CUSTOMER_TBL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return CustomerTbl.CUSTOMER_TBL.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerTblRecord value1(String value) {
		setGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerTblRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerTblRecord value3(Integer value) {
		setAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerTblRecord values(String value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerTblRecord
	 */
	public CustomerTblRecord() {
		super(CustomerTbl.CUSTOMER_TBL);
	}

	/**
	 * Create a detached, initialised CustomerTblRecord
	 */
	public CustomerTblRecord(String guid, String name, Integer age) {
		super(CustomerTbl.CUSTOMER_TBL);

		setValue(0, guid);
		setValue(1, name);
		setValue(2, age);
	}
}
