/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity;


import com.example.dao.entity.tables.CustomerInfoTbl;
import com.example.dao.entity.tables.CustomerTbl;
import com.example.dao.entity.tables.records.CustomerInfoTblRecord;
import com.example.dao.entity.tables.records.CustomerTblRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CustomerTblRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
	public static final UniqueKey<CustomerInfoTblRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CustomerTblRecord> CONSTRAINT_B = createUniqueKey(CustomerTbl.CUSTOMER_TBL, CustomerTbl.CUSTOMER_TBL.GUID);
		public static final UniqueKey<CustomerInfoTblRecord> CONSTRAINT_C = createUniqueKey(CustomerInfoTbl.CUSTOMER_INFO_TBL, CustomerInfoTbl.CUSTOMER_INFO_TBL.CUSTOMER_ID, CustomerInfoTbl.CUSTOMER_INFO_TBL.KEY);
	}
}
