/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity;


import com.example.dao.entity.tables.CustomerInfoTbl;
import com.example.dao.entity.tables.CustomerTbl;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.CUSTOMER_TBL
	 */
	public static final CustomerTbl CUSTOMER_TBL = com.example.dao.entity.tables.CustomerTbl.CUSTOMER_TBL;

	/**
	 * The table PUBLIC.CUSTOMER_INFO_TBL
	 */
	public static final CustomerInfoTbl CUSTOMER_INFO_TBL = com.example.dao.entity.tables.CustomerInfoTbl.CUSTOMER_INFO_TBL;
}
