/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables.daos;


import com.example.dao.entity.tables.CustomerInfoTbl;
import com.example.dao.entity.tables.records.CustomerInfoTblRecord;

import java.util.List;

import javax.annotation.Generated;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;

import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Component
public class CustomerInfoTblDao extends DAOImpl<CustomerInfoTblRecord, com.example.dao.entity.tables.pojos.CustomerInfoTbl, Record2<String, String>> {

	@Resource
	private DSLContext dsl;

	@PostConstruct
	private void init() {
		System.out.println(this.getClass().getName() + " init jooq config");
		this.setConfiguration(this.dsl.configuration());
	}
	/**
	 * Create a new CustomerInfoTblDao without any configuration
	 */
	public CustomerInfoTblDao() {
		super(CustomerInfoTbl.CUSTOMER_INFO_TBL, com.example.dao.entity.tables.pojos.CustomerInfoTbl.class);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<String, String> getId(com.example.dao.entity.tables.pojos.CustomerInfoTbl object) {
		return compositeKeyRecord(object.getCustomerId(), object.getKey());
	}

	/**
	 * Fetch records that have <code>CUSTOMER_ID IN (values)</code>
	 */
	public List<com.example.dao.entity.tables.pojos.CustomerInfoTbl> fetchByCustomerId(String... values) {
		return fetch(CustomerInfoTbl.CUSTOMER_INFO_TBL.CUSTOMER_ID, values);
	}

	/**
	 * Fetch records that have <code>KEY IN (values)</code>
	 */
	public List<com.example.dao.entity.tables.pojos.CustomerInfoTbl> fetchByKey(String... values) {
		return fetch(CustomerInfoTbl.CUSTOMER_INFO_TBL.KEY, values);
	}

	/**
	 * Fetch records that have <code>VAL IN (values)</code>
	 */
	public List<com.example.dao.entity.tables.pojos.CustomerInfoTbl> fetchByVal(String... values) {
		return fetch(CustomerInfoTbl.CUSTOMER_INFO_TBL.VAL, values);
	}
}
