/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CUSTOMER_TBL", schema = "PUBLIC")
public class CustomerTbl implements Serializable {

	private static final long serialVersionUID = -433563927;

	private String  guid;
	private String  name;
	private Integer age;

	public CustomerTbl() {}

	public CustomerTbl(CustomerTbl value) {
		this.guid = value.guid;
		this.name = value.name;
		this.age = value.age;
	}

	public CustomerTbl(
		String  guid,
		String  name,
		Integer age
	) {
		this.guid = guid;
		this.name = name;
		this.age = age;
	}

	@Id
	@Column(name = "GUID", unique = true, nullable = false, length = 100)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "AGE", nullable = false, precision = 10)
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CustomerTbl (");

		sb.append(guid);
		sb.append(", ").append(name);
		sb.append(", ").append(age);

		sb.append(")");
		return sb.toString();
	}
}
