/**
 * This class is generated by jOOQ
 */
package com.example.dao.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CUSTOMER_INFO_TBL", schema = "PUBLIC", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"CUSTOMER_ID", "KEY"})
})
@IdClass(CustomerInfoKey.class)
public class CustomerInfoTbl implements Serializable {

	private static final long serialVersionUID = 964754968;

	private String customerId;
	private String key;
	private String val;

	public CustomerInfoTbl() {}

	public CustomerInfoTbl(CustomerInfoTbl value) {
		this.customerId = value.customerId;
		this.key = value.key;
		this.val = value.val;
	}

	public CustomerInfoTbl(
		String customerId,
		String key,
		String val
	) {
		this.customerId = customerId;
		this.key = key;
		this.val = val;
	}

	@Id
	@Column(name = "CUSTOMER_ID", nullable = false, length = 100)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Id
	@Column(name = "KEY", nullable = false, length = 100)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "VAL", nullable = false, length = 100)
	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CustomerInfoTbl (");

		sb.append(customerId);
		sb.append(", ").append(key);
		sb.append(", ").append(val);

		sb.append(")");
		return sb.toString();
	}
}
